

mod_id=scraps
curse_slug=scraps
curse_id=621390
mod_version=0.1.1
mod_name=scraps
mod_group_id=com.lothrazar.scraps
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=

flib_version=0.2.0
flib_file=8117455

